server:
  port: 8080

spring:
  application:
    name: codexray-api

logging:
  level:
    root: INFO
    com.codexray: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
